version: "3.8"

services:
  app:
    container_name: user-activity-logs
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI_LOCAL=mongodb://root:password@mongo:27017/App-Logs?authSource=admin
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=activity-logs-topic
    networks:
      - user-activity-logs-network
    depends_on:
      - mongo
      - kafka
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./mongo-data:/data/db"
    networks:
      - user-activity-logs-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - user-activity-logs-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - TOPIC_AUTO_CREATE=false
      - DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - user-activity-logs-network

networks:
  user-activity-logs-network:
    driver: bridge
